name: Bug Report
description: "Report something that's broken."
body:
  - type: markdown
    attributes:
      value: "Thank you for submitting bug reports. If you notice improper DocBlock, PHPStan, or IDE warnings, do not create a GitHub issue. Instead, please submit a pull request to fix the problem."
  - type: input
    attributes:
      label: PHP Version
      description: Provide the PHP version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
